name: workflow contexts

on: [push]

jobs:
  my-context:
    runs-on: ubuntu-latest
    steps:
      - name: My Step
        run: echo "Hello $MY_ACTION"
        env:
          MY_ACTION: ${{ github.action }}
      - name: Step 2
        run: echo ${{ vars.large_runner }}
      - name: Step 3
        run: echo ${{ github.actor }}